config/routes.rb
Rails.application.routes.draw do
  get '/404', :to => 'errors#not_found'
  get '/505', :to => 'errors#internal_server_error'

  root "home#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Add and destroy song to/from favorites
  post '/song:id/favorite', to: 'songs#favorite', as: :favorite
  delete '/song:id/favorite', to: 'favorites#destroy', as: :destroy
   
  
  namespace :admin do
      resource :dashboard, only: [:show]
      resources :albums
      resources :artists
      resources :songs
      resources :genres
  end  


  resources :users, only: [:new, :create]
  resources :albums
  resources :artists
  resources :songs
  resources :genres
  resources :playlists
  resources :playlist_songs
  resources :favorites

end

app/views/shared/_add_song_to_playlist.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">×</button>
      <h3>Add song to playlist</h3>
    </div>
    <div class="modal-body">
      <%= form_for PlaylistSong.new, remote: true, url: playlist_songs_path, method: :post, id: 'myForm' do |form| %>
  		  <input id="songId" name="songId" type="hidden" />
        <%= form.collection_select :playlist_id, Playlist.where(user_id: current_user.id), :id, :name, { prompt: 'Choose Playlist' }, class: 'form-control' %>
        <br>
        <%= form.submit 'Save', method: :post, class: 'btn btn-block btn-primary' %>
        <br>
        <%= link_to 'Create a playlist', new_playlist_path %>
      <% end %> 
    </div>
  </div>
</div>

app/views/shared/_admin_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-custom navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   
<!-- Brand -->
 <div class="container">
  <%= link_to image_tag("/assets/brand/FP.svg", alt: "FavPlay"), root_path, class: 'navbar-brand d-inline-block align-top' %>

<!-- Links -->
<div class="collapse navbar-collapse" id="nav-content">   
  <ul class="navbar-nav ml-auto">
      <% unless logged_in? %>    
        <li class="nav-item">
          <li class="nav-link" href="#"><%= link_to 'Log in', login_path %></li>
        </li>  
          <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Sign up', new_user_path %></li>
        </li> 
      </ul> 
      <% else %>  
      <ul class="navbar-nav mx-auto justify-content-center"> 
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Artists', admin_artists_path, class:'nav-orange' %></li>
         </li>  
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Songs', admin_songs_path, class:'nav-orange' %></li>
         </li>
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Albums',admin_albums_path, class:'nav-orange' %></li>
         </li>    
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Genres',admin_genres_path , class:'nav-orange'%></li>
         </li>
      </ul> 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="Preview" href="#" role="button" aria-haspopup="true" aria-expanded="false">Logged in as <%= current_user.username %>
        </a>

      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% if current_user.admin? || current_user.superadmin? %>
          <a class="dropdown-item" ><%= link_to 'Dashboard', admin_dashboard_path, class:'drop-nav' %></a>
        <% end %>
          <a class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class:'drop-nav' %></a>
        </ul>    
      </div> 
    <% end %>
  </div>
 </div> 
</nav>

app/views/shared/_favorite.html.erb
  <%= link_to favorite_songs_path(song_id: song), method: :post, remote: true do %>
          <i class="fa fa-heart-o" aria-hidden="true" rel="tooltip" data-placement="top" title="Add to favorites"></i>
    <% end %>

app/views/shared/_flash.html.erb
<div class="container" id="notice_wrapper">
 <% flash.each do |name, msg| %>
  <div class="<%= name %>" id="notice">
    <p class="notice"><%= msg %></p>
  </div>
 <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="fixed bg-inverse text-white py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-6 align-self-end small">
                @2017 FavPlay
            </div>
        </div>
    </div>
</footer> 

app/views/shared/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-custom navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   
<!-- Brand -->
 <div class="container">
  <%= link_to image_tag("/assets/brand/FP.svg", alt: "FavPlay"), root_path, class: 'navbar-brand d-inline-block align-top' %>

<!-- Links -->
<div class="collapse navbar-collapse" id="nav-content">   
  <ul class="navbar-nav ml-auto">
      <% unless logged_in? %>    
        <li class="nav-item">
          <li class="nav-link" href="#"><%= link_to 'Log in', login_path %></li>
        </li>  
          <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Sign up', new_user_path %></li>
        </li> 
      </ul> 
      <% else %>  
      <ul class="navbar-nav mx-auto justify-content-center">
        <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Playlists', playlists_path, class:'nav-orange' %></li>
         </li> 
        <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Favorites', favorites_path, class:'nav-orange' %></li>
         </li> 
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Artists', artists_path, class:'nav-orange' %></li>
         </li>  
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Songs', songs_path, class:'nav-orange' %></li>
         </li>
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Albums', albums_path, class:'nav-orange' %></li>
         </li>    
         <li class="nav-item">
            <li class="nav-link" href="#"><%= link_to 'Genres', genres_path , class:'nav-orange'%></li>
         </li>
      </ul> 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="Preview" href="#" role="button" aria-haspopup="true" aria-expanded="false">Logged in as <%= current_user.username %>
        </a>

      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% if current_user.admin? || current_user.superadmin? %>
          <a class="dropdown-item" ><%= link_to 'Dashboard',admin_dashboard_path, class:'drop-nav' %></a>
        <% end %>
          <a class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class:'drop-nav' %></a>
        </ul>    
      </div> 
    <% end %>
  </div>
 </div> 
</nav>

app/views/shared/_new_playlist.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Add New Playlist</h4>
      </div>
      <div class="modal-body">
        <%= form_for Playlist.new do |form| %>
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
          <br>
          <%= form.label :description %>
          <%= form.text_field :description, class: 'form-control' %>
          <br>
          <%= form.hidden_field :user_id, :value => current_user.id %>
          <%= form.submit 'Save', method: :post, remote: true, class: 'btn btn-block btn-primary' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div>
</div>

app/views/shared/_top_songs.html.erb
<% @top_songs.each_with_index do |song, i| %>
 <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= (i+1) %>&nbsp;&nbsp;<%= link_to song.name, song_path(song), class:'nav-orange' %></li>
  </ul>
<% end %>

app/views/shared/_unfavorite.html.erb
  <%= link_to favorite_song_path(song), method: :delete, remote: true do %>
          <i class="fa fa-heart" aria-hidden="true" rel="tooltip" data-placement="top" title="Remove from favorites"></i>
        <% end %>

app/views/shared/_validation_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <% model.errors.full_messages.each do |error| %>
      <p><%= error %></p>
    <% end %>
  </div>
<% end %>