config/routes.rb
Rails.application.routes.draw do
  get '/404', :to => 'errors#not_found'
  get '/505', :to => 'errors#internal_server_error'

  root "home#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Add and destroy song to/from favorites
  post '/song:id/favorite', to: 'songs#favorite', as: :favorite
  delete '/song:id/favorite', to: 'favorites#destroy', as: :destroy
   
  
  namespace :admin do
      resource :dashboard, only: [:show]
      resources :albums
      resources :artists
      resources :songs
      resources :genres
  end  


  resources :users, only: [:new, :create]
  resources :albums
  resources :artists
  resources :songs
  resources :genres
  resources :playlists
  resources :playlist_songs
  resources :favorites

end

app/models/genre.rb
class Genre < ApplicationRecord
	belongs_to :user

	has_many :songs, dependent: :destroy
	has_many :albums, dependent: :destroy
	has_many :artists, dependent: :destroy
  
  validates :name, presence: true, length: {maximum: 25}
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
	before_action :authorize_for_admins
	before_action :find_genre, { only: [:edit, :update, :show, :destroy] }

	def index
		@genres = Genre.all
	end
	
	def new
		@genre = Genre.new
	end
	
	def create
		@genre = Genre.new(genre_params)
		@genre.user_id = current_user.id
    if @genre.save
			redirect_to admin_genres_path, success: 'Genre created successfully'
		else
			render :new
		end
  end

  def edit
  	unless @genre.user_id == current_user.id || current_user.superadmin?
  		redirect_to root_path, danger: 'Permisson denied!'
  	end
  end

  def update
  	if @genre.update(genre_params)
			redirect_to admin_genres_path, success: 'Genre successfully updated!'
		else
			render :edit
		end
	end

	def show
		@album = @genre.albums
		@song = @genre.songs
	end

  def destroy
  	unless @genre.user_id == current_user.id || current_user.superadmin?
  		redirect_to root_path, danger: 'Permisson denied!'
  	else 	
	  	@genre.destroy
	  	redirect_to admin_genres_path, danger: 'Genre deleted!'
	  end	
  end

  private

  def genre_params
  	params.require(:genre).permit(:name);
  end
  
  def find_genre
  	@genre = Genre.find(params[:id])
  end
end 		 				

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	before_action :authorize
	before_action :find_genre, { only: [:show] }

	def index
		@genres = Genre.all
	end
	
	def show
		@albums = @genre.albums
		@songs = @genre.songs
	end

	private

	def find_genre
		@genre = Genre.find(params[:id])
	end	
end 		 				

app/views/admin/genres/_form.html.erb
<%= form_for [:admin, @genre] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class:'form-control' %>
	<%= error_for :name, @genre.errors %>
	<br>	
	<%= f.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-primary' %>
<% end %>	

app/views/admin/genres/_genre.html.erb
<tr>
  <th scope="row"><%= link_to genre.id, genre_path(genre) %></th>
  <td><%= link_to genre.name, admin_genre_path(genre)%></td>
  <td><%= link_to genre.songs.count, songs_path(genre.songs)%></td>
  <td><%= link_to genre.artists.count, artists_path(genre.artists)%></td> 
  <td><%= link_to genre.albums.count, albums_path(genre.albums)%></td>
  
</tr>

app/views/admin/genres/edit.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4">
    <br>
    <h1>Update genre</h1>
    <br>

    <%= render 'shared/validation_messages', model: @genre %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<%= render 'shared/flash' %>
<div class="row mt-5">
  <div class="container">
  	<div class="col-md-2 offset-md-10">
      <% if current_user.admin? || current_user.superadmin? %>
	 	  <%= link_to 'Add new genre', new_admin_genre_path, class: 'btn btn-primary' %>
      <% end %>
	 	</div>
	 	<br>
	 	<table class="table pt-5">
      <thead>
        <tr>
          <th>#</th>
          <th>Genres</th>
          <th>Songs</th>
          <th>Artists</th>
          <th>Albums</th>
        </tr>
      </thead>
      <tbody>
        <%= render @genres %>
      </tbody>
    </table>
	</div>
</div>

app/views/admin/genres/new.html.erb
<div class="container p-5">
	<div class="col-md-4 offset-md-4">
		<h3>Add a genre</h3>
		<br>
		
		<%= render 'shared/validation_messages', model: @genre %>
		<%= render 'form' %>	
	</div>
</div>

app/views/admin/genres/show.html.erb
<div class="container mt-5">
	<br>
  <div class="row">
  	<div class="col-sm-6 col-md-4 col-lg-3 mt-4">
  		<div class="card">
	    <h2><%= @genre.name %></h2>
      <% if @genre.user_id == current_user.id || current_user.superadmin? %>
      <%= link_to 'Edit', edit_genre_path, class:'btn btn-sm btn-secondary' %>
      <%= link_to 'Delete', admin_genre_path(@genre), method: :delete, data: {confirm: "Are you sure?"}, class:'btn btn-sm btn-danger'%>
      <% end %>
		  </div>
  	</div>	  
   </div>
    <h2 class="lead mt-5">Songs that are in <%= @genre.name %> genre.</h2>
    <table class="table pt-5 mt-4">
      <thead>
        <tr>
          <th>#</th>
          <th></th>
          <th>Song</th>
          <th>Artist</th>
          <th>Album</th>
          <th>Length</th>
          <th>Genre</th>
        </tr>
      </thead>
      <tbody>
        <%= render @song %>
      </tbody>
    </table>
  </div>
</div> 