config/routes.rb
Rails.application.routes.draw do
  get '/404', :to => 'errors#not_found'
  get '/505', :to => 'errors#internal_server_error'

  root "home#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Add and destroy song to/from favorites
  post '/song:id/favorite', to: 'songs#favorite', as: :favorite
  delete '/song:id/favorite', to: 'favorites#destroy', as: :destroy
   
  
  namespace :admin do
      resource :dashboard, only: [:show]
      resources :albums
      resources :artists
      resources :songs
      resources :genres
  end  


  resources :users, only: [:new, :create]
  resources :albums
  resources :artists
  resources :songs
  resources :genres
  resources :playlists
  resources :playlist_songs
  resources :favorites

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	helper_method :sort_column, :sort_direction

	include SongHelper
	
	def index
		@songs = Song.search(params[:term]).order("#{sort_column} #{sort_direction}").paginate(:page => params[:page], :per_page => 10)
		@latest_albums = Album.order('created_at DESC').first(5)
		@top_songs = Song.order('favorites_count DESC').limit(5)
	end

	private

  def sortable_columns
  	["name", "length", "artist_id", "album_id", "genre_id"]
  end
  
  def sort_column
  	sortable_columns.include?(params[:column]) ? params[:column] : "name"
  end
  
  def sort_direction
  	%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"	
  end 						
end		

app/views/home/_latest_albums.html.erb
	
<% @latest_albums.each do |album| %>
		<div class="media">
			<%= link_to album_path(album) do %>
			 <%= image_tag album.img_url, class: "card-img-top" %>
		  </div>		         
		   <% end %>
		  <div class="media-body">
		    <h5 class="mt-2 mb-0"><%= link_to album.name, album_path(album) %></h5>
		    <p class="pb-3"><%= link_to album.artist.name, artist_path(album.artist), class:'artist' %></p>
      <% end %>
		  </div>
		</div>  
	</div>
</div>

app/views/home/_popular_songs.html.erb
<% @top_songs.each_with_index do |song, i| %>
 <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= (i+1) %>&nbsp;&nbsp;<%= link_to song.name, song_path(song), class:'nav-orange' %></li>
  </ul>
<% end %>

app/views/home/_songs.html.erb
<br>
<br>
<div class="col-sm-8">
	<h3 class="text-muted pb-2">Latest songs added</h3>
	<%= form_tag(root_path, method: :get, class: 'input-group pb-3') do %>
	<%= text_field_tag :term, params[:term], class: 'form-control', placeholder: 'Search for a song..' %>
	<span class="input-group-btn">
	<%= submit_tag 'Search', name: nil, class: 'btn btn-secondary' %>
	</span>
	<% end %>
</div>
<table class="table pt-5 mt-3">
  <thead>
    <tr>
      <th>#</th>
      <th width="10%"></th>
      <th><%= sort_link "name", "Song" %></th>
      <th><%= sort_link "artist_id", "Artist" %></th>
      <th><%= sort_link "album_id", "Album" %></th>
      <th><%= sort_link "length" %></th>
      <th><%= sort_link "genre_id", "Genre" %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
 <% @songs.each do |song| %>
		<tr>
		  <th scope="row"><%= song.id %></th>
		<% if logged_in? %>
	 <td>
	    <div class="">
	      <%= link_to favorite_path(id: song.id), method: :post , remote: true do %>
	      <div class="like-btn text-center" song_id="<%= song.id %>">
	        <span class="<%= song.heart_class(current_user) %>"></span>
	      </div>
	      <% end %>
	    </div>
		  </td>
		  <td class="light-text"><%= link_to song.name, song_path(song) %></td>
		  <td class="light-text"><%= link_to song.artist.name, artist_path(song.artist_id)%></td>
		  <td class="light-text"><%= link_to song.album.name, album_path(song.album_id)%></td>
		  <td class="light-text"><%= link_to song.length, song_path(song)%></td>
		  <td class="light-text"><%= link_to song.genre.name, genre_path(song.genre_id)%></td>
		    <td>
		      <%= link_to song.youtube_link, target: :_blank do %>
		       <i class="fa fa-play" aria-hidden="true" rel="tooltip" data-placement="top" title="Press to play on YouTube"></i>
		    </td>  
		    <td>
		      <a data-toggle="modal" data-target="#addSong" data-id="<%= song.id %>" title="Add this song to playlist" class="open-AddSong" href="#addSong"><i class="fa fa-plus" aria-hidden="true" rel="tooltip" data-placement="top" title="Add to playlist"></i></a>

		      <div class="modal fade" id="addSong">
		        <%= render 'shared/add_song_to_playlist' %>
		      </div>
		     <% end %> 
		    </td>
		  <% end %>
		  </tr>
		<% end %>
  </tbody>
</table>
<div>
   <%= will_paginate(@songs, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %> 
</div>

app/views/home/index.html.erb
<% unless logged_in? %>
<section id="splash-blue">
	<div class="layer">
		<div class="container">
			<div class="row">
				<div class="col-md-12 jumbotron">
					<div class="to-center text-center">
						<h2 class="display-1">FavPlay</h2>
						<br>
						<p class="lead">Create ultimate playlists with your favorite artists!</p>
						<p>Create an account with us, or simply log in below!</p>
						<p class="lead">
							<%= link_to 'Log in', login_path, class: "btn btn-primary" %>
							<%= link_to 'Sign up!', new_user_path, class: "btn btn-primary" %>
						</p>	
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
	<% else %>    
<div class="container">	
	<div class="row h-100">
    <main class="col py-3">
            <div class="row">
                <div class="col">
                    <div class="tab-content py-3">
                        <div class="tab-pane active" id="tab1" role="tabpanel">
                            <div class="col-xs-2 col-sm-8 col-md-12">
                             <%= render 'songs'%>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-10 mt-5 m-b-20">
                    <div class="card card-inverse bg-inverse mb-3">
                        <div class="card-block">
                            <h3 class="card-title">Popular Songs</h3>
                          <%= render 'popular_songs' %>
                        </div>
                    </div>
                    <div class="card bg-faded border-0">
                        <div class="card-block">
                            <h3 class="card-title">Latest Albums</h3>
                          <%= render 'latest_albums' %>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<%= render 'shared/footer' %>
<% end %>