config/routes.rb
Rails.application.routes.draw do
  get '/404', :to => 'errors#not_found'
  get '/505', :to => 'errors#internal_server_error'

  root "home#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Add and destroy song to/from favorites
  post '/song:id/favorite', to: 'songs#favorite', as: :favorite
  delete '/song:id/favorite', to: 'favorites#destroy', as: :destroy
   
  
  namespace :admin do
      resource :dashboard, only: [:show]
      resources :albums
      resources :artists
      resources :songs
      resources :genres
  end  


  resources :users, only: [:new, :create]
  resources :albums
  resources :artists
  resources :songs
  resources :genres
  resources :playlists
  resources :playlist_songs
  resources :favorites

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_one :user
  
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs

  validates :name, presence: true, length: {maximum: 15}
  validates :description, presence: true 
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authorize
	before_action :find_playlist, { only: [:edit, :update, :show, :destroy] }


	def index
		@playlists = current_user.playlists
		@playlist = Playlist.new
	end
	
	def new
		@playlist = Playlist.new
	end	


	def create
		@playlist = Playlist.new(playlist_params)
		@playlist.user_id = current_user.id
			respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, success: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
        format.js { flash[:notice] = 'Playlist was created successfully!' }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, success: 'Playlist successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
        format.js { flash[:notice] = 'Playlist was updated successfully!' } 
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end


  def show
  end


  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_path, danger: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
      format.js { flash[:alert] = 'Playlist was successfully destroyed.'}
    end
  end
 				
	private

	def playlist_params
		params.require(:playlist).permit(:name, :description, :user_id);
	end

	def find_playlist
		@playlist = Playlist.find(params[:id])
	end
end		

app/views/playlists/_form.html.erb
<%= form_for @playlist do |f| %>
<%= f.label :name %>
<%= f.text_field :name, class:'form-control' %>
<br>
<%= f.label :description %>
<%= f.text_area :description, class:'form-control' %>
<br>
<%= f.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/playlists/_playlist.html.erb
<div class="col-md-4 p-3" id="playlist_<%= playlist.id %>">
  <div class="card"><!-- Panel Info -->
    <div class="card-block">
      <h3 class="card-title"><%= link_to playlist.name, playlist_path(playlist) %></h3>
      <p class="card-text">Created: <%= time_ago_in_words(playlist.created_at) %> ago</p>
      <p class="card-text"><%= playlist.description %></p>
      <br>
      <div class="btn-group" role="group" aria-label="...">
          <button type="button" class="btn btn-sm btn-secondary" data-toggle="modal" data-target="#myupdateplaylist_<%= playlist.id %>">
            Edit
          </button>
          <%= link_to 'Delete', playlist_path(playlist), method: :delete, class: "btn btn-sm btn-danger", remote: true %>
      </div>
    </div>
  </div>

  <!-- Modal - update posts -->
    <%= form_for(playlist, :method => :put, remote: true) do |f| %>
    <div class="modal fade" id="myupdateplaylist_<%= playlist.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit</h4>
        </div>
        <div class="modal-body">
          <div class="field">
          <%= f.label :name %><br>
          <%= f.text_area :name, class: "form-control" %>
          </div>
          <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" id="myupdatebutton_<%= playlist.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
         <%= submit_tag 'Update', class: 'btn btn-block btn-default' %>
        </div>
      </div>
    </div>
  </div>
 <% end %>
 <!-- Modal -->
</div>

app/views/playlists/_song.html.erb
<% if logged_in? %>
<table class="table pt-5">
  <thead>
		<tr>
		  <th>#</th>
		  <th width="10px"></th>
  		<th>Name</th>
  		<th>Length</th>
		</tr>
	</thead>
	<tbody>
  <% @playlist.songs.each_with_index do |song, i| %>
   <tr>
   <th scope="row" width="10px"><%= (i+1) %></th>
	 <td>
	    <div class="">
	      <%= link_to favorite_path(id: song.id), method: :post , remote: true do %>
	      <div class="like-btn text-center" song_id="<%= song.id %>">
	        <span class="<%= song.heart_class(current_user) %>"></span>
	      </div>
	      <% end %>
	    </div>
      </td>
			<td><%= link_to song.name, song_path(song) %></td>	
			<td><%= song.length %></td>		
			<td>
				<%= link_to song.youtube_link, target: :_blank do %>
				<i class="fa fa-play" aria-hidden="true" rel="tooltip" data-placement="top" title="Press to play on YouTube"></i>
				<% end %>
      </td>
      <td>
      	<%= link_to playlist_song_path(song_id: song.id, playlist_id: @playlist.id), method: :delete do %>
				<i class="fa fa-times" aria-hidden="true"></i>
				<% end %>
      </td>
			<% end %>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/playlists/create.js.erb
$("#mynewplaylist").modal('hide');
$(".playlist_name").val('');
$(".playlist_description").val('');


$("#container_playlists").prepend('<%= j render @playlist %>');
$("#playlist_<%= @playlist.id %>").hide().fadeIn(1000);
$("#notice").html(" <%= flash[:notice] %>");

app/views/playlists/destroy.js.erb
alert("Are you sure you want to delete this playlist?");
$("#playlist_<%= @playlist.id %>").fadeOut(500, function(){
	$(this).remove();
	$("#notice").html("<%= flash[:alert] %>");
});

app/views/playlists/edit.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4">
    <br>
    <h1>Update Playlist</h1>
    <br>

    <%= render 'form' %>
  </div>
</div>

app/views/playlists/index.html.erb
<div class="container p-5">
	<div class="bg-faded col-md-6" id="notice">
	  <%= display_flash :notice %>
	</div> 
	<br>
	<div class="col-md-3">
    <h4>Playlists</h4>
  </div>
	<div class="row">
		<div class="col-md-2 offset-md-10">
		  <!-- Button trigger modal -->
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mynewplaylist">
		   Add new playlist
		  </button>
		</div>
	</div>

	<br>
	<hr>	

		<div class="row" id="container_playlists">
			<%= render @playlists %>
		</div>	
			<!-- Modal -->
		 	<%= form_for(@playlist, remote: true) do |f| %>
				<div class="modal fade" id="mynewplaylist" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">

				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLabel">Playlist</h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>

				      <div class="modal-body">
				      	<div class="field">
					       <%= f.label :name %>
								 <%= f.text_field :name, class:'form-control playlist_name' %>
								</div>	

								<div class="field">
					       <%= f.label :description %>
								 <%= f.text_area :description, class:'form-control playlist_description' %>
								</div>  
				      </div>

				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				         <%= submit_tag "Create", class: "btn btn-primary" %>
				      </div>
				    </div>
				  </div>
			</div>
		<% end %>
	  <!-- Modal	 -->

	</div>

app/views/playlists/new.html.erb
<div class="container p-5">
	<div class="col-md-4 offset-md-4">
		<h3>Create new playlist</h3>
		<br>
		
		<%= render 'shared/validation_messages', model: @playlist %>
		<%= render 'form' %>	
	</div>
</div>

app/views/playlists/show.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col-md-4"> 
		<p id="notice"><%= notice %></p>
		 <h3><%= @playlist.name %></h3>
		 </div>
		 <div class="col-md-9 push-md-9">
			<%= link_to "Add songs", songs_path, class:'btn btn-primary' %>
		 </div>
		</div>		  
		<br>	
		<div class="row">
			<div class="col-md-10"> 
		  <%= render 'song' %>
	    <%= link_to 'Edit', edit_playlist_path(@playlist) %> |
			<%= link_to 'Back', playlists_path %>
      </div>
    </div> 
</div>

app/views/playlists/update.js.erb
$("#myupdateplaylist_<%= @playlist.id %>").modal('hide');

$("#playlist_<%= @playlist.id %>").fadeOut(500, function(){

	$(this).remove();
	$("#container_playlists").prepend('<%= j render @playlist %>');
});

$("#notice").html(" <%= flash[:notice] %>");
	